# Generated by Django 4.1.7 on 2023-04-12 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_complate_order_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quntity',
            new_name='quantity',
        ),
    ]
